[package]
name = "rust-puppetdb-cli"
version = "0.1.3"
description = "PuppetDB CLI tool in rust."
readme = "README.md"
documentation = "http://ajroetker.github.io/rust-puppetdb-cli/index.html"
repository = "https://github.com/ajroetker/rust-puppetdb-cli"
license-file = "LICENSE"
keywords = ["puppet", "puppetdb", "puppetdb-cli"]
authors = ["Andrew Roetker <andrew.roetker@puppetlabs.com>"]

[lib]
name = "puppetdb"
path = "src/lib.rs"

[[bin]]
name = "puppet-db"
path = "src/db.rs"

[[bin]]
name = "puppet-query"
path = "src/query.rs"

[dependencies]
beautician = "0.1.*"
hyper = "0.8.*"
docopt = "0.6.*"
rustc-serialize = "0.3.*"
url = "0.5.*"

[dev-dependencies]
tempfile = "2.1.1"

[dependencies.openssl]
version = "0.7.*"
features = ["tlsv1_2"]

[dependencies.multipart]
version = "0.6.*"
default-features = false
features = ["hyper", "client"]

[dependencies.puppet_access]
optional = true
path = "puppet_access"

[features]
default = []
puppet-access = ["puppet_access"]
